# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\soulsnoW\myfolder\mywindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from multiprocessing import Process, Queue
from worker import Worker

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.market = QtWidgets.QTabWidget(self.centralwidget)
        self.market.setObjectName("market")
        self.kospi = QtWidgets.QWidget()
        self.kospi.setObjectName("kospi")
        self.gridLayout = QtWidgets.QGridLayout(self.kospi)
        self.gridLayout.setObjectName("gridLayout")
        self.kospichart = PlotWidget(self.kospi)
        self.kospichart.setObjectName("kospichart")
        self.gridLayout.addWidget(self.kospichart, 0, 0, 1, 1)
        self.market.addTab(self.kospi, "")
        self.kosdaq = QtWidgets.QWidget()
        self.kosdaq.setObjectName("kosdaq")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.kosdaq)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.kosdaqchart = QtWidgets.QGraphicsView(self.kosdaq)
        self.kosdaqchart.setObjectName("kosdaqchart")
        self.gridLayout_6.addWidget(self.kosdaqchart, 0, 0, 1, 1)
        self.market.addTab(self.kosdaq, "")
        self.future = QtWidgets.QWidget()
        self.future.setObjectName("future")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.future)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.futurechart = QtWidgets.QGraphicsView(self.future)
        self.futurechart.setObjectName("futurechart")
        self.gridLayout_9.addWidget(self.futurechart, 0, 0, 1, 1)
        self.market.addTab(self.future, "")
        self.gridLayout_10.addWidget(self.market, 0, 0, 1, 1)
        self.hoga_order = QtWidgets.QGroupBox(self.centralwidget)
        self.hoga_order.setObjectName("hoga_order")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.hoga_order)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.hogawindow = QtWidgets.QTableWidget(self.hoga_order)
        self.hogawindow.setObjectName("hogawindow")
        self.hogawindow.setColumnCount(0)
        self.hogawindow.setRowCount(0)
        self.gridLayout_8.addWidget(self.hogawindow, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.hoga_order, 0, 1, 2, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gwansim = QtWidgets.QTabWidget(self.widget)
        self.gwansim.setObjectName("gwansim")
        self.tab_gwansim = QtWidgets.QWidget()
        self.tab_gwansim.setObjectName("tab_gwansim")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_gwansim)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_gwansim = QtWidgets.QTableWidget(self.tab_gwansim)
        self.table_gwansim.setAlternatingRowColors(True)
        self.table_gwansim.setRowCount(20)
        self.table_gwansim.setColumnCount(5)
        self.table_gwansim.setObjectName("table_gwansim")
        item = QtWidgets.QTableWidgetItem()
        self.table_gwansim.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_gwansim.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_gwansim.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_gwansim.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_gwansim.setHorizontalHeaderItem(4, item)
        self.table_gwansim.horizontalHeader().setCascadingSectionResizes(False)
        self.table_gwansim.horizontalHeader().setDefaultSectionSize(95)
        self.table_gwansim.horizontalHeader().setHighlightSections(False)
        self.table_gwansim.horizontalHeader().setSortIndicatorShown(False)
        self.table_gwansim.horizontalHeader().setStretchLastSection(True)
        self.table_gwansim.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.table_gwansim, 0, 0, 1, 1)
        self.gwansim.addTab(self.tab_gwansim, "")
        self.tab_account = QtWidgets.QWidget()
        self.tab_account.setObjectName("tab_account")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_account)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table_account = QtWidgets.QTableWidget(self.tab_account)
        self.table_account.setAlternatingRowColors(True)
        self.table_account.setRowCount(20)
        self.table_account.setColumnCount(7)
        self.table_account.setObjectName("table_account")
        item = QtWidgets.QTableWidgetItem()
        self.table_account.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_account.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_account.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_account.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_account.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_account.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_account.setHorizontalHeaderItem(6, item)
        self.table_account.horizontalHeader().setDefaultSectionSize(90)
        self.table_account.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.table_account, 0, 0, 1, 1)
        self.gwansim.addTab(self.tab_account, "")
        self.tab_acc_p = QtWidgets.QWidget()
        self.tab_acc_p.setObjectName("tab_acc_p")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_acc_p)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_acc_p)
        self.tableWidget.setRowCount(16)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_11.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gwansim.addTab(self.tab_acc_p, "")
        self.gridLayout_4.addWidget(self.gwansim, 1, 0, 1, 1)
        self.control = QtWidgets.QTabWidget(self.widget)
        self.control.setObjectName("control")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.control.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.control.addTab(self.tab_5, "")
        self.gridLayout_4.addWidget(self.control, 0, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 100)
        self.gridLayout_4.setRowStretch(1, 400)
        self.gridLayout_10.addWidget(self.widget, 0, 2, 2, 1)
        self.code_chart = QtWidgets.QTabWidget(self.centralwidget)
        self.code_chart.setObjectName("code_chart")
        self.teb_daily = QtWidgets.QWidget()
        self.teb_daily.setObjectName("teb_daily")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.teb_daily)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.day_chart = PlotWidget(self.teb_daily)
        self.day_chart.setObjectName("day_chart")
        self.gridLayout_5.addWidget(self.day_chart, 0, 0, 1, 1)
        self.code_chart.addTab(self.teb_daily, "")
        self.tab_weekly = QtWidgets.QWidget()
        self.tab_weekly.setObjectName("tab_weekly")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_weekly)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.weekly_chart = QtWidgets.QGraphicsView(self.tab_weekly)
        self.weekly_chart.setObjectName("weekly_chart")
        self.gridLayout_7.addWidget(self.weekly_chart, 0, 0, 1, 1)
        self.code_chart.addTab(self.tab_weekly, "")
        self.gridLayout_10.addWidget(self.code_chart, 1, 0, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 200)
        self.gridLayout_10.setColumnStretch(1, 100)
        self.gridLayout_10.setColumnStretch(2, 100)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.market.setCurrentIndex(2)
        self.gwansim.setCurrentIndex(1)
        self.control.setCurrentIndex(1)
        self.code_chart.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # self.table_gwansim_input()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.market.setTabText(self.market.indexOf(self.kospi), _translate("MainWindow", "kospi"))
        self.market.setTabText(self.market.indexOf(self.kosdaq), _translate("MainWindow", "kosdaq"))
        self.market.setTabText(self.market.indexOf(self.future), _translate("MainWindow", "선물"))
        self.hoga_order.setTitle(_translate("MainWindow", "호가주문"))
        item = self.table_gwansim.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "종목명"))
        item = self.table_gwansim.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "현재가"))
        item = self.table_gwansim.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "대비"))
        item = self.table_gwansim.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "등락율"))
        item = self.table_gwansim.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "거래량"))
        self.gwansim.setTabText(self.gwansim.indexOf(self.tab_gwansim), _translate("MainWindow", "관심종목"))
        item = self.table_account.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "종목명"))
        item = self.table_account.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "보유수량"))
        item = self.table_account.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "매입가"))
        item = self.table_account.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "현재가"))
        item = self.table_account.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "수익률"))
        item = self.table_account.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "평가손익"))
        item = self.table_account.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "평가금액"))
        self.gwansim.setTabText(self.gwansim.indexOf(self.tab_account), _translate("MainWindow", "계좌잔고"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "계좌번호"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "추정에수금"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "수익률"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "평가손익"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "매입금액"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "평가금액"))
        self.gwansim.setTabText(self.gwansim.indexOf(self.tab_acc_p), _translate("MainWindow", "계좌평가"))
        self.control.setTabText(self.control.indexOf(self.tab_4), _translate("MainWindow", "수신로그"))
        self.control.setTabText(self.control.indexOf(self.tab_5), _translate("MainWindow", "모드설정"))
        self.code_chart.setTabText(self.code_chart.indexOf(self.teb_daily), _translate("MainWindow", "일봉"))
        self.code_chart.setTabText(self.code_chart.indexOf(self.tab_weekly), _translate("MainWindow", "분봉"))

from pyqtgraph import PlotWidget
import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)

    queue = Queue()
    # Process(target=Worker, args=(queue,), daemon=True).start()
    # worker = Worker(queue)
    # worker.start()
    # Process(target=Worker, args=(queue,), daemon=False).start()

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    # sys.exit(app.exec_())
    app.exec_()

